spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: guest
    password: guest
destinations:
  queues:
    NYSE:
      exchange: nyse
      routing-key: NYSE
    IBOV:
      exchange: ibov
      routing-key: IBOV
  topics:
    weather:
      exchange: alerts
      routing-key: WEATHER